# You are given two strings s and t. String t is generated by random shuffling string s
# and then add one more letter at a random position. Return the letter that was added to t.

# Author: Kaustav Ghosh

class Solution(object):
    def findTheDifference(self, s, t):
        res = 0
        for ch in s + t:
            res ^= ord(ch)
        return chr(res)
