-- Author: Kaustav Ghosh
-- https://leetcode.com/problems/build-the-equation/
-- Premium

-- SELECT CONCAT(
--     GROUP_CONCAT(
--         CASE
--             WHEN factor > 0 THEN CONCAT('+', factor)
--             ELSE CAST(factor AS CHAR)
--         END,
--         CASE
--             WHEN power = 0 THEN ''
--             WHEN power = 1 THEN 'X'
--             ELSE CONCAT('X^', power)
--         END
--         ORDER BY power DESC
--         SEPARATOR ''
--     ),
--     '=0'
-- ) AS equation
-- FROM Terms;
